---
title: "Figures-in-English"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Test

```{r mrg_UBCF}
test <- data_article_UBCF %>% group_by(ResponseId) %>% 
                            gather(key = "Artikel", value ="User_Bewertung", loop1.1_1, loop1.2_1, loop1.3_1, loop1.4_1) %>% 
                            gather(key = "Pre_Prediction", value = "RS_Pre_Prediction", pre_pred_A1_round, pre_pred_A2_round, pre_pred_A3_round, pre_pred_A4_round) %>% 
                            mutate(Artikel = str_remove(Artikel, "loop1.")) %>% 
                            mutate(Artikel = str_remove(Artikel, "_1")) %>% 
                            mutate(Pre_Prediction = str_remove(Pre_Prediction, "pre_pred_A")) %>% 
                            mutate(Pre_Prediction = str_remove(Pre_Prediction, "_round")) %>% 
                            filter (Artikel == Pre_Prediction) %>% 
                            select(ResponseId, Artikel, User_Bewertung, RS_Pre_Prediction)

testB <- data_article_UBCF %>% group_by(ResponseId) %>% 
                            gather(key = "Artikel", value ="User_Bewertung", loop1.1_1, loop1.2_1, loop1.3_1, loop1.4_1) %>% 
                            gather(key = "Post_Prediction", value = "RS_Post_Prediction", post_pred_A1_round, post_pred_A2_round, post_pred_A3_round, post_pred_A4_round) %>%
                            mutate(Artikel = str_remove(Artikel, "loop1.")) %>% 
                            mutate(Artikel = str_remove(Artikel, "_1")) %>% 
                            mutate(Post_Prediction = str_remove(Post_Prediction, "post_pred_A")) %>% 
                            mutate(Post_Prediction = str_remove(Post_Prediction, "_round")) %>% 
                            filter (Artikel == Post_Prediction) %>% 
                            select(ResponseId, Artikel, User_Bewertung, RS_Post_Prediction)

testC <- inner_join(test, testB, by = c("ResponseId","Artikel","User_Bewertung"))


testD <- testC  %>%  
  mutate(Distance_Pretest = RS_Pre_Prediction - User_Bewertung) %>% 
  mutate(Distance_Posttest = RS_Post_Prediction - User_Bewertung) %>% 
  mutate(ResponseId_Article = paste(ResponseId,Artikel,sep = "_")) %>% 
  ungroup() %>% 
  select(ResponseId_Article,Distance_Pretest, Distance_Posttest,Artikel) %>% 
  #filter(Distance_Pretest != Distance_Posttest) %>% 
  pivot_longer(cols = c(Distance_Pretest , Distance_Posttest), names_to = "Test", values_to = "Distance")

a <- ggstatsplot::ggwithinstats(
  data = testD,
  x = Test,
  y = Distance,
  #title = "Comparison between pre- and posttest",
  xlab = "a) UBCF",
  ylab = "",
  pairwise.comparisons = T,
  pairwise.display = "s",
  mean.plotting = F,
  title = "Distance between prediction ",
  #ggtheme = ggthemes::theme_fivethirtyeight(),
  ggstatsplot.layer = FALSE,
  messages = FALSE,
  results.subtitle = FALSE,
) + scale_y_continuous(breaks = seq(-3, 3, by = 1)) +
    scale_x_discrete(limits = c("Distance_Pretest","Distance_Posttest"))

```

```{r gg_ubcf}
gg_ubcf_cor <- data_article_UBCF %>% select(ResponseId, Pretest = cor_user_UBCF_pre, Posttest = cor_user_UBCF_post) %>% pivot_longer(cols = c(Pretest, Posttest), names_to = "RecSys", values_to = "correlation")


b<- ggstatsplot::ggwithinstats(
  data = gg_ubcf_cor,
  x = RecSys,
  y = correlation,
  xlab = "c) UBCF",
  ylab = "",
  pairwise.comparisons = TRUE,
  pairwise.display = "significant",
  pairwise.annotation = "p.value",
  title = "Correlation between prediction ",
  #ggtheme = ggthemes::theme_fivethirtyeight(),
  ggstatsplot.layer = FALSE,
  results.subtitle = FALSE,
  messages = FALSE
)  + scale_x_discrete(limits = c("Pretest","Posttest"))

```

```{r mrg_svd}
test <- data_article_SVD %>% group_by(ResponseId) %>% 
                            gather(key = "Artikel", value ="User_Bewertung", loop2.1_1, loop2.2_1, loop2.3_1, loop2.4_1) %>% 
                            gather(key = "Pre_Prediction", value = "RS_Pre_Prediction", pre_pred_B1_round, pre_pred_B2_round, pre_pred_B3_round, pre_pred_B4_round) %>% 
                            mutate(Artikel = str_remove(Artikel, "loop2.")) %>% 
                            mutate(Artikel = str_remove(Artikel, "_1")) %>% 
                            mutate(Pre_Prediction = str_remove(Pre_Prediction, "pre_pred_B")) %>% 
                            mutate(Pre_Prediction = str_remove(Pre_Prediction, "_round")) %>% 
                            filter (Artikel == Pre_Prediction) %>% 
                            select(ResponseId, Artikel, User_Bewertung, RS_Pre_Prediction)

testB <- data_article_SVD %>% group_by(ResponseId) %>% 
                            gather(key = "Artikel", value ="User_Bewertung", loop2.1_1, loop2.2_1, loop2.3_1, loop2.4_1) %>% 
                            gather(key = "Post_Prediction", value = "RS_Post_Prediction", post_pred_B1_round, post_pred_B2_round, post_pred_B3_round, post_pred_B4_round) %>% 
                            mutate(Artikel = str_remove(Artikel, "loop2.")) %>% 
                            mutate(Artikel = str_remove(Artikel, "_1")) %>% 
                            mutate(Post_Prediction = str_remove(Post_Prediction, "post_pred_B")) %>% 
                            mutate(Post_Prediction = str_remove(Post_Prediction, "_round")) %>% 
                            filter (Artikel == Post_Prediction) %>% 
                            select(ResponseId, Artikel, User_Bewertung, RS_Post_Prediction)

testC <- inner_join(test, testB, by = c("ResponseId","Artikel","User_Bewertung"))

testD <- testC  %>%  
  mutate(Distance_Pretest = RS_Pre_Prediction - User_Bewertung) %>% 
  mutate(Distance_Posttest = RS_Post_Prediction - User_Bewertung) %>% 
  mutate(ResponseId_Article = paste(ResponseId,Artikel,sep = "_")) %>% 
  ungroup() %>% 
  select(ResponseId_Article,Distance_Pretest, Distance_Posttest,Artikel) %>% 
  #filter(Distance_Pretest != Distance_Posttest) %>% 
  #filter((Distance_Pretest > Distance_Posttest & Distance_Posttest >= 0)|(Distance_Pretest < Distance_Posttest & Distance_Posttest <= 0)) %>% 
  pivot_longer(cols = c(Distance_Pretest , Distance_Posttest), names_to = "Test", values_to = "Distance")

c<- ggstatsplot::ggwithinstats(
  data = testD,
  x = Test,
  y = Distance,
  #title = "Comparison between pre- and posttest",
  xlab = "b) SVD",
  ylab = "",
  sort = "descending", # ordering groups along the x-axis based on
  sort.fun = mean, # values of `y` variable
  pairwise.comparisons = T,
  pairwise.display = "s",
  mean.plotting = F,
  title = "and rating",
  #ggtheme = ggthemes::theme_fivethirtyeight(),
  ggstatsplot.layer = FALSE,
  messages = FALSE,
  results.subtitle = FALSE,
)  + scale_y_continuous(breaks = c(-3,-2,-1,0,1,2,3)) +
     scale_x_discrete(limits = c("Distance_Pretest","Distance_Posttest"))

```

```{r gg_svd}
gg_svd_cor <- data_article_SVD %>% select(ResponseId, Pretest = cor_user_SVD_pre, Posttest = cor_user_SVD_post) %>% pivot_longer(cols = c(Pretest, Posttest), names_to = "RecSys", values_to = "correlation")

d <- ggstatsplot::ggwithinstats(
  data = gg_svd_cor,
  x = RecSys,
  y = correlation,
  xlab = "d) SVD",
  ylab = "",
  sort = "ascending", # ordering groups along the x-axis based on
  sort.fun = median, # values of `y` variable
  pairwise.comparisons = TRUE,
  pairwise.display = "s",
  pairwise.annotation = "p",
  title = "and rating",
  #ggtheme = ggthemes::theme_fivethirtyeight(),
  ggstatsplot.layer = FALSE,
  results.subtitle = FALSE,
  messages = FALSE
) + scale_x_discrete(limits = c("Pretest","Posttest"))

gridExtra::grid.arrange(a,b,c,d, layout_matrix = rbind(c(1,3,2,4)))
```