---
title: "Code-Archiv"
author: "Stefan"
date: "8 11 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
library(sjPlot)
library(sjlabelled)
library(kableExtra)
library(knitr)
library(apastats)
```

# Bildungs Labor
```{r}
data_demograph  %>% ggplot() + 
                    aes(x = factor(school), fill = factor(gender)) + 
                    geom_bar(position = "dodge",) + 
                    scale_x_discrete(labels=c(`1` = "keine Schulausbildung", `2` = "Volks-/Hauptschulabschluss", `3` = "Realschulabschluss", `4` = "(Fach-)Abitur", `5` = "Sonstiges")) +
                    ylab("Anzahl") + 
                    scale_fill_discrete(name="Geschlecht",labels=c("männlich", "weiblich")) +
                    coord_flip() 
```

```{r}
# x- Achse: school
# y- Achse: ..prop.. → Wahrscheinlichkeiten
# facet_grid → teilt den Graph in mehrere Teile
# fill: färbt die Skalen ein, fügt Farb-Legende hinzu.
# geom_text: fügt Beschriftungen an einzelnen Balken hinzu.

ggplot(data=data_demograph, aes(x=school)) + 
    geom_bar(aes(y = ..prop.., fill = factor(..x..))) +
    geom_text(aes( label = scales::percent(..prop..), y= ..prop.. ), stat= "count", vjust = -0.1) +
    labs(y = "Prozent", x="") +
    coord_cartesian(ylim=c(0,0.8))+
    scale_fill_discrete(name= "Abschluss", guide = guide_legend(reverse = TRUE), labels = c("keine Schulausbildung",
                                                            "Volks-/Hauptschulabschluss",
                                                            "Realschulabschluss",
                                                            "(Fach-)Abitur",
                                                            "Sonstiges")) +
    facet_grid(data_demograph$gender, labeller = as_labeller(c(`1` = "männlich", `2` = "weiblich"))) +
    scale_y_continuous(labels = scales::percent) +
    scale_x_discrete()
```

```{r}
data_demograph  %>% ggplot(aes(x = school,
                               y = ..prop..,
                               fill = factor(gender))) + 
                    geom_bar(position = "dodge") + 
                    geom_text(aes(label = scales::percent(..prop..),      y= ..prop.. ),
                              stat= "count", position = position_dodge(width = 1), hjust = -0.1) +
                    labs(y = "Anteil in %", x="Abschluss") +
                    scale_fill_manual(values = c("skyblue","royalblue"),
                                      name="Geschlecht",
                                      labels=c("männlich", "weiblich")) +
                    guides(fill = guide_legend(reverse = TRUE)) +
                    coord_flip(ylim=c(0,0.8))+
                    scale_x_reverse(breaks = 1:5,labels = c("keine Schulausbildung",
                                                            "Volks-/Hauptschulabschluss",
                                                            "Realschulabschluss",
                                                            "(Fach-)Abitur",
                                                            "Sonstiges")) +
                    scale_y_continuous(labels = scales::percent)


```

# Topic Labor

```{r}
# Finde alle NA und ersetzte NA durch 9 
data_topicSelect$interestingTopic[is.na(data_topicSelect$interestingTopic)] <-9
data_topicSelect  %>% ggplot(aes(x = interestingTopic,
                               y = ..prop..,
                               fill = factor(data_demograph$gender))) + 
                    geom_bar(position = "dodge") + 
                    geom_text(aes(label = scales::percent(..prop..),      y= ..prop.. ),
                    stat= "count", position = position_dodge(width = 1), hjust = -0.1) +
                    labs(y = "Anteil in %", x="Thema") +
                    scale_fill_manual(values = c("skyblue","royalblue"),
                                      name="Geschlecht",
                                      labels=c("männlich", "weiblich")) +
                    guides(fill = guide_legend(reverse = TRUE)) +
                    coord_flip(ylim=c(0,0.33))+
                    scale_x_reverse(breaks = 1:9,labels = c("Politik","Games","Wirtschaft","Kultur","Lifestyle","Computer & Technik","Netzpolitik","Wissenschaft","keine Angabe")) +
                    scale_y_continuous(labels = scales::percent)

```


# Boxplot Labor

```{r}
ggplot(data_kut,aes(x=data_cleaned$gender, y=KUT, group=as.numeric(data_cleaned$gender)))+
      geom_boxplot()+
      labs(x ="Geschlecht", y = "") +
      scale_x_continuous(breaks = 1:2, labels = c("männlich","weiblich")) +
      coord_cartesian(ylim = c(1,6)) +
      geom_jitter(shape=16, position=position_jitter(0.05))

# Mehrere Spalten in zwei Spalten (Bezeichnung, Wert) zusammenfassen:
# pivot_longer(cols = NAME_ALLER_SPALTEN,names_to = "BEZEICHNUNG", values_to = "WERT")
data_empf_gen <- data_RS_einschaetzung %>% select(-ResponseId) %>% pivot_longer(cols= starts_with("einsch"), names_to = "Empfehlungssystem", values_to = "Genauigkeit")

# Boxplot mit Punktgraph
ggplot(data_empf_gen, aes(x=Empfehlungssystem, y=Genauigkeit))+
      geom_boxplot() +
      #scale_x_discrete(labels = c("A","B","C","D","E","F")) +
      geom_dotplot(binaxis='y', method= "histodot", stackdir='centerwhole', binwidth=1.2, stackratio = 1.4, fill = "royalblue", color = "darkblue") +
      scale_y_continuous(labels = scales::unit_format(suffix =" %"))

# Boxplot mit Violingraph
ggplot(data_empf_gen, 
       aes(x=reorder(Empfehlungssystem, Genauigkeit, FUN = mean), 
           y=Genauigkeit))+
      geom_violin(alpha = 0.6, 
                  fill = "lightblue") +
      geom_boxplot(alpha = 0.8) +
      labs(x = "Empfehlungssystem") +
      scale_x_discrete(labels = c("Random","Popular","IBCF","UBCF","Content","Hybrid")) +
      scale_y_continuous(labels = scales::unit_format(suffix =" %"))
```


```{r}
data_pub_gen <- data_publishing %>% select(-ResponseId)
data_pub_gen$RS_dataPublishing_1 <- as.numeric(data_pub_gen$RS_dataPublishing_1)
data_pub_gen$RS_dataPublishing_2 <- as.numeric(data_pub_gen$RS_dataPublishing_2)
data_pub_gen$RS_dataPublishing_3 <- as.numeric(data_pub_gen$RS_dataPublishing_3)
data_pub_gen$RS_dataPublishing_4 <- as.numeric(data_pub_gen$RS_dataPublishing_4)
data_pub_gen$RS_dataPublishing_5 <- as.numeric(data_pub_gen$RS_dataPublishing_5)
data_pub_gen$RS_dataPublishing_6 <- as.numeric(data_pub_gen$RS_dataPublishing_6)
data_pub_gen$RS_dataPublishing_7 <- as.numeric(data_pub_gen$RS_dataPublishing_7)

data_pub_gen <- data_pub_gen %>% pivot_longer(cols= c(starts_with("RS")), names_to = "Datentyp", values_to = "Bereitschaft")

ggplot(data_pub_gen, 
       aes(x=reorder(Datentyp, Bereitschaft, FUN = mean), 
           y=Bereitschaft))+
      geom_violin(alpha = 0.6, 
                  fill = "lightblue") +
      geom_boxplot(alpha = 0.7) +
      labs(x = "Datentyp") +
      scale_x_discrete(labels = c("Standort","Politische Einstellung","Religion","Geschlecht/Alter","Bewertung","Hobby","Themengebiete")) +
      scale_y_continuous(breaks = seq(1, 6, by = 1)) +
      coord_cartesian(ylim = c(1,6)) 
```

```{r}
ggplot(data_priv,aes(x=data_cleaned$gender, y=RS_Privacy_Consern, group=as.numeric(data_cleaned$gender)))+
      geom_violin(alpha = 0.6, fill = "lightblue") +
      geom_boxplot(alpha = 0.7)+
      labs(x ="Geschlecht", y = "Einstellung zur Privatsphäre eines Empfehlungssystems") +
      scale_x_continuous(breaks = 1:2, labels = c("männlich","weiblich")) +
      scale_y_continuous(breaks = seq(1, 6, by = 0.5)) +
      coord_cartesian(ylim = c(1,6)) 
```

# Confidence Intervall (bootstrapped)
```{r}
df %>% select(BF_O, BF_C) %>% psych::pairs.panels(lm = TRUE, cor = T, jiggle = T, stars = T, ci = T)

test_cor <- data_bigFive %>% select(-ResponseId) %>% psych::cor.ci() 

test_cor$ci %>% 
  rownames_to_column() %>% 
  bind_cols(data.frame("r"= test_cor$means)) %>% 
  ggplot() + 
  aes(x = reorder(rowname, r, FUN = mean) , y = r, ymin=`low.e`, ymax = `up.e`) + 
  geom_errorbar(width = 0.2) + geom_point() + 
  geom_line() +
  scale_y_continuous(limits = c(-1,1))
```

# ggwithinstats Labor Korrelation
```{r gg_ubcf}
gg_ubcf_cor <- data_article_UBCF %>% select(ResponseId, Pretest = cor_user_UBCF_pre, Posttest = cor_user_UBCF_post) %>% pivot_longer(cols = c(Pretest, Posttest), names_to = "RecSys", values_to = "correlation")

ggstatsplot::ggwithinstats(
  data = gg_ubcf_cor,
  x = RecSys,
  y = correlation,
  sort = "ascending", # ordering groups along the x-axis based on
  sort.fun = median, # values of `y` variable
  pairwise.comparisons = TRUE,
  pairwise.display = "s",
  pairwise.annotation = "p",
  title = "UBCF - Korrelation zwischen Vorhersage und Realwert",
  ggtheme = ggthemes::theme_fivethirtyeight(),
  ggstatsplot.layer = FALSE,
  messages = FALSE
)
```

```{r gg_svd}
gg_svd_cor <- data_article_SVD %>% select(ResponseId, Pretest = cor_user_SVD_pre, Posttest = cor_user_SVD_post) %>% pivot_longer(cols = c(Pretest, Posttest), names_to = "RecSys", values_to = "correlation")

ggstatsplot::ggwithinstats(
  data = gg_svd_cor,
  x = RecSys,
  y = correlation,
  sort = "ascending", # ordering groups along the x-axis based on
  sort.fun = median, # values of `y` variable
  pairwise.comparisons = TRUE,
  pairwise.display = "s",
  pairwise.annotation = "p",
  title = "SVD - Korrelation zwischen Vorhersage und Realwert",
  ggtheme = ggthemes::theme_fivethirtyeight(),
  ggstatsplot.layer = FALSE,
  messages = FALSE
)
```

# ggwithinstats Labor Abstand

```{r mrg_svd}
test <- data_article_SVD %>% group_by(ResponseId) %>% 
                            gather(key = "Artikel", value ="User_Bewertung", loop2.1_1, loop2.2_1, loop2.3_1, loop2.4_1) %>% 
                            gather(key = "Pre_Prediction", value = "RS_Pre_Prediction", pre_pred_B1_round, pre_pred_B2_round, pre_pred_B3_round, pre_pred_B4_round) %>% 
                            mutate(Artikel = str_remove(Artikel, "loop2.")) %>% 
                            mutate(Artikel = str_remove(Artikel, "_1")) %>% 
                            mutate(Pre_Prediction = str_remove(Pre_Prediction, "pre_pred_B")) %>% 
                            mutate(Pre_Prediction = str_remove(Pre_Prediction, "_round")) %>% 
                            filter (Artikel == Pre_Prediction) %>% 
                            select(ResponseId, Artikel, User_Bewertung, RS_Pre_Prediction)

testB <- data_article_SVD %>% group_by(ResponseId) %>% 
                            gather(key = "Artikel", value ="User_Bewertung", loop2.1_1, loop2.2_1, loop2.3_1, loop2.4_1) %>% 
                            gather(key = "Post_Prediction", value = "RS_Post_Prediction", post_pred_B1_round, post_pred_B2_round, post_pred_B3_round, post_pred_B4_round) %>% 
                            mutate(Artikel = str_remove(Artikel, "loop2.")) %>% 
                            mutate(Artikel = str_remove(Artikel, "_1")) %>% 
                            mutate(Post_Prediction = str_remove(Post_Prediction, "post_pred_B")) %>% 
                            mutate(Post_Prediction = str_remove(Post_Prediction, "_round")) %>% 
                            filter (Artikel == Post_Prediction) %>% 
                            select(ResponseId, Artikel, User_Bewertung, RS_Post_Prediction)

testC <- inner_join(test, testB, by = c("ResponseId","Artikel","User_Bewertung"))

testD <- testC  %>%  
  mutate(Abstand_Pretest = RS_Pre_Prediction - User_Bewertung) %>% 
  mutate(Abstand_Posttest = RS_Post_Prediction - User_Bewertung) %>% 
  mutate(ResponseId_Article = paste(ResponseId,Artikel,sep = "_")) %>% 
  ungroup() %>% 
  select(ResponseId_Article,Abstand_Pretest, Abstand_Posttest,Artikel) %>% 
  #filter(Abstand_Pretest != Abstand_Posttest) %>% 
  #filter((Abstand_Pretest > Abstand_Posttest & Abstand_Posttest >= 0)|(Abstand_Pretest < Abstand_Posttest & Abstand_Posttest <= 0)) %>% 
  pivot_longer(cols = c(Abstand_Pretest , Abstand_Posttest), names_to = "Test", values_to = "Abstand")

ggstatsplot::ggwithinstats(
  data = testD,
  x = Test,
  y = Abstand,
  title = "SVD - Vergleich zwischen Pre- und Posttest",
  xlab = "Empfehlungssystem",
  ylab = "Abstand zwischen Vorhersage und Bewertung",
  sort = "ascending", # ordering groups along the x-axis based on
  sort.fun = mean, # values of `y` variable
  pairwise.comparisons = T,
  pairwise.display = "s",
  mean.plotting = F,
  #title = "SVD - Korrelation zwischen Vorhersage und Realwert",
  #ggtheme = ggthemes::theme_fivethirtyeight(),
  ggstatsplot.layer = FALSE,
  messages = FALSE,
  results.subtitle = FALSE,
)  + scale_y_continuous(breaks = c(-3,-2,-1,0,1,2,3))

testE <- testC  %>%  
  mutate(Abstand_Pretest = RS_Pre_Prediction - User_Bewertung) %>% 
  mutate(Abstand_Posttest = RS_Post_Prediction - User_Bewertung) %>% 
  mutate(ResponseId_Article = paste(ResponseId,Artikel,sep = "_")) %>% 
  ungroup() %>% 
  select(ResponseId_Article,Abstand_Pretest, Abstand_Posttest,Artikel) %>% 
  filter(Abstand_Pretest != Abstand_Posttest) %>% 
  #filter((Abstand_Pretest > Abstand_Posttest & Abstand_Posttest >= 0)|(Abstand_Pretest < Abstand_Posttest & Abstand_Posttest <= 0)) %>% 
  pivot_longer(cols = c(Abstand_Pretest , Abstand_Posttest), names_to = "Test", values_to = "Abstand")

ggstatsplot::ggwithinstats(
  data = testE,
  x = Test,
  y = Abstand,
  title = "SVD - Vergleich zwischen Pre- und Posttest",
  xlab = "Empfehlungssystem",
  ylab = "Abstand zwischen Vorhersage und Bewertung",
  sort = "ascending", # ordering groups along the x-axis based on
  sort.fun = mean, # values of `y` variable
  pairwise.comparisons = T,
  pairwise.display = "s",
  mean.plotting = F,
  #title = "SVD - Korrelation zwischen Vorhersage und Realwert",
  #ggtheme = ggthemes::theme_fivethirtyeight(),
  ggstatsplot.layer = FALSE,
  messages = FALSE,
  results.subtitle = FALSE,
) + scale_y_continuous(breaks = c(-3,-2,-1,0,1,2,3))

skimr::inline_hist(testC$RS_Pre_Prediction - testC$User_Bewertung, n_bins = 7)
skimr::inline_hist(testC$RS_Post_Prediction - testC$User_Bewertung, n_bins = 5)
table(testC$RS_Pre_Prediction - testC$User_Bewertung)
table(testC$RS_Post_Prediction - testC$User_Bewertung)

```

```{r mrg_UBCF}
test <- data_article_UBCF %>% group_by(ResponseId) %>% 
                            gather(key = "Artikel", value ="User_Bewertung", loop1.1_1, loop1.2_1, loop1.3_1, loop1.4_1) %>% 
                            gather(key = "Pre_Prediction", value = "RS_Pre_Prediction", pre_pred_A1_round, pre_pred_A2_round, pre_pred_A3_round, pre_pred_A4_round) %>% 
                            mutate(Artikel = str_remove(Artikel, "loop1.")) %>% 
                            mutate(Artikel = str_remove(Artikel, "_1")) %>% 
                            mutate(Pre_Prediction = str_remove(Pre_Prediction, "pre_pred_A")) %>% 
                            mutate(Pre_Prediction = str_remove(Pre_Prediction, "_round")) %>% 
                            filter (Artikel == Pre_Prediction) %>% 
                            select(ResponseId, Artikel, User_Bewertung, RS_Pre_Prediction)

testB <- data_article_UBCF %>% group_by(ResponseId) %>% 
                            gather(key = "Artikel", value ="User_Bewertung", loop1.1_1, loop1.2_1, loop1.3_1, loop1.4_1) %>% 
                            gather(key = "Post_Prediction", value = "RS_Post_Prediction", post_pred_A1_round, post_pred_A2_round, post_pred_A3_round, post_pred_A4_round) %>%
                            mutate(Artikel = str_remove(Artikel, "loop1.")) %>% 
                            mutate(Artikel = str_remove(Artikel, "_1")) %>% 
                            mutate(Post_Prediction = str_remove(Post_Prediction, "post_pred_A")) %>% 
                            mutate(Post_Prediction = str_remove(Post_Prediction, "_round")) %>% 
                            filter (Artikel == Post_Prediction) %>% 
                            select(ResponseId, Artikel, User_Bewertung, RS_Post_Prediction)

testC <- inner_join(test, testB, by = c("ResponseId","Artikel","User_Bewertung"))


testD <- testC  %>%  
  mutate(Abstand_Pretest = RS_Pre_Prediction - User_Bewertung) %>% 
  mutate(Abstand_Posttest = RS_Post_Prediction - User_Bewertung) %>% 
  mutate(ResponseId_Article = paste(ResponseId,Artikel,sep = "_")) %>% 
  ungroup() %>% 
  select(ResponseId_Article,Abstand_Pretest, Abstand_Posttest,Artikel) %>% 
  #filter(Abstand_Pretest != Abstand_Posttest) %>% 
  pivot_longer(cols = c(Abstand_Pretest , Abstand_Posttest), names_to = "Test", values_to = "Abstand")

ggstatsplot::ggwithinstats(
  data = testD,
  x = Test,
  y = Abstand,
  title = "UBCF - Vergleich zwischen Pre- und Posttest",
  xlab = "Empfehlungssystem",
  ylab = "Abstand zwischen Vorhersage und Bewertung",
  sort = "ascending", # ordering groups along the x-axis based on
  sort.fun = mean, # values of `y` variable
  pairwise.comparisons = T,
  pairwise.display = "s",
  mean.plotting = F,
  #title = "SVD - Korrelation zwischen Vorhersage und Realwert",
  #ggtheme = ggthemes::theme_fivethirtyeight(),
  ggstatsplot.layer = FALSE,
  messages = FALSE,
  results.subtitle = FALSE,
) + scale_y_continuous(breaks = seq(-3, 3, by = 1))

testE <- testC  %>%  
  mutate(Abstand_Pretest = RS_Pre_Prediction - User_Bewertung) %>% 
  mutate(Abstand_Posttest = RS_Post_Prediction - User_Bewertung) %>% 
  mutate(ResponseId_Article = paste(ResponseId,Artikel,sep = "_")) %>% 
  ungroup() %>% 
  select(ResponseId_Article,Abstand_Pretest, Abstand_Posttest,Artikel) %>% 
  filter(Abstand_Pretest != Abstand_Posttest) %>% 
  #filter((Abstand_Pretest > Abstand_Posttest & Abstand_Posttest >= 0)|(Abstand_Pretest < Abstand_Posttest & Abstand_Posttest <= 0)) %>% 
  pivot_longer(cols = c(Abstand_Pretest , Abstand_Posttest), names_to = "Test", values_to = "Abstand")

ggstatsplot::ggwithinstats(
  data = testE,
  x = Test,
  y = Abstand,
  title = "UBCF - Vergleich zwischen Pre- und Posttest",
  xlab = "Empfehlungssystem",
  ylab = "Abstand zwischen Vorhersage und Bewertung",
  sort = "ascending", # ordering groups along the x-axis based on
  sort.fun = mean, # values of `y` variable
  pairwise.comparisons = T,
  pairwise.display = "s",
  mean.plotting = F,
  #title = "SVD - Korrelation zwischen Vorhersage und Realwert",
  #ggtheme = ggthemes::theme_fivethirtyeight(),
  ggstatsplot.layer = FALSE,
  messages = FALSE,
  results.subtitle = FALSE,
)  + scale_y_continuous(breaks = c(-3,-2,-1,0,1,2,3))

skimr::inline_hist(testC$RS_Pre_Prediction - testC$User_Bewertung, n_bins = 7)
skimr::inline_hist(testC$RS_Post_Prediction - testC$User_Bewertung, n_bins = 7)

sum(testC$RS_Pre_Prediction != testC$RS_Post_Prediction)


```


