---
title: "Auswertung Masterarbeit"
author: "Stefan Ahlers"
date: "11/5/2019"
output:
  html_document: 
    toc: true
    toc_float: true
    code_folding : hide
    df_print : paged
  pdf_document: default
---

<!--- Läd die benötigten Daten -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
library(sjPlot)
library(sjlabelled)
library(kableExtra)
library(knitr)
library(apastats)
```

# Daten laden und bereinigen.
<!--- Läd die Daten und speichert sie in "raw" -->
```{r read_data}
raw <- read_sav(file= "data/191104-data.sav")
```

<!--- Bereinigt den Datensatz und speichert ihn in "cleaned" -

TODO: O-Sterne Bewertungen in 1-Sterne Bewertungen umformatieren.

-->
```{r cleaning}
cleaned <- raw %>% filter(Progress == 100) %>% select(-StartDate,-EndDate,-Status,-IPAddress,-Duration__in_seconds_,-Progress,-Finished,-RecordedDate,-RecipientEmail,-RecipientFirstName,-RecipientLastName,-ExternalReference,-LocationLatitude,-LocationLongitude,-DistributionChannel,-UserLanguage,-ResponseID.0,-age.0,-gender.0,-topic,-randomTopicQuestion,-title,-body,-itemID,-subtitle,-date,-recsys,-rating,-iteration)  # Es werden nur die vollständigen Datensätze ausgewertet; überflüssige Spalten entfernt

```

<!--- Auswertung der Big Five 
      1 = negativ
      6 = positiv
-->
```{r bigFive}
big_df <- cleaned %>% select(starts_with("bigf"))

#big_df %>% map(get_label) %>% str_split("-") -> labels_bf 
#for (label in labels_bf){
#  print(label[2])
#}

keys_bf  <- list(offenheit = c("-bigFive_5", "bigFive_10"),
                 gewissenhaft  = c("-bigFive_3", "bigFive_8"),
                 extraversion = c("-bigFive_1", "bigFive_6"),
                 vertraeglich = c("bigFive_2", "-bigFive_7"),
                 neuro = c("bigFive_4", "-bigFive_9"))

result <- psych::scoreItems(keys = keys_bf , big_df)
result
#result$scores

data <- bind_cols(cleaned, as.data.frame(result$scores))
```

<!--- Auswertung des KUT 
    1 = sehr geringer KUT
    6 = sehr hoher KUT
-->
```{r KUT}

kut_df <- cleaned %>% select(starts_with("kut"))

#kut_df %>% map(get_label) %>% str_split("-") -> labels_bf 

#for (label in labels_bf){
#  print(label[3])
#}

keys_bf  <- list(KUT = c("-kut_1", "-kut_2", "kut_3", "-kut_4", "-kut_5", "-kut_6", "kut_7", "kut_8", "kut_9", "kut_10"))

result_alpha <- psych::alpha(kut_df, check.keys = TRUE)
result_alpha

result <- psych::scoreItems(keys = keys_bf , kut_df)
result

#result$scores

data_kut <- bind_cols(cleaned, as.data.frame(result$scores))
```

<!--- Auswertung des RS Privacy 
      1 = sehr geringes Vertrauen in die Privatsphäre
      6 = sehr großes Vertrauen in der Privatsphäre
-->
```{r Privacy_RS}

privacy_df <- cleaned %>% select(starts_with("RS_privacy"))

#privacy_df %>% map(get_label) %>% str_split("-") -> labels_bf 
#for (label in labels_bf){
#print(label[3])
#}

keys_bf  <- list(RS_Privacy_Consern = c("-RS_privacy_1","-RS_privacy_2","RS_privacy_3","-RS_privacy_4","RS_privacy_5"))

result_alpha <- psych::alpha(privacy_df, check.keys = TRUE)
result_alpha

result <- psych::scoreItems(keys = keys_bf , privacy_df)
result
result$scores

data_priv <- bind_cols(cleaned, as.data.frame(result$scores))
```

<!--- Auswertung Bewertungen Anlernen
      1 = sehr schlecht
      5 = sehr gut
-->
```{r Bewertung_Anlernung}
anlernen_df <- cleaned %>% select(starts_with("Anlernen"))

keys_bf  <- list(Anlernen_Artikel_Bewertungen = c("Anlernen1_1","Anlernen2_1","Anlernen3_1","Anlernen4_1","Anlernen5_1","Anlernen6_1","Anlernen7_1"))

result_alpha <- psych::alpha(anlernen_df, check.keys = TRUE)
result_alpha

result <- psych::scoreItems(keys = keys_bf , anlernen_df)
result
#result$scores

data_anlernen <- bind_cols(cleaned, as.data.frame(result$scores))
```

<!--- Auswertung Bewertungen UBCF Artikel
      1 = sehr schlecht
      5 = sehr gut
-->
```{r Bewertung_UBCF}
UBCF_df <- cleaned %>% select(starts_with("loop1"))

keys_bf  <- list(UBCF_Artikel_Bewertungen = c("loop1.1_1","loop1.2_1","loop1.3_1","loop1.4_1"))

result_alpha <- psych::alpha(UBCF_df, check.keys = TRUE)
result_alpha

result <- psych::scoreItems(keys = keys_bf , UBCF_df)
result
#result$scores

data_UBCF <- bind_cols(cleaned, as.data.frame(result$scores))
```

<!--- Auswertung Bewertungen SVD Artikel
      1 = sehr schlecht
      5 = sehr gut
-->
```{r Bewertung_UBCF}
SVD_df <- cleaned %>% select(starts_with("loop2"))

keys_bf  <- list(UBCF_Artikel_Bewertungen = c("loop2.1_1","loop2.2_1","loop2.3_1","loop2.4_1"))

result_alpha <- psych::alpha(SVD_df, check.keys = TRUE)
result_alpha

result <- psych::scoreItems(keys = keys_bf , SVD_df)
result
result$scores

data_SVD <- bind_cols(cleaned, as.data.frame(result$scores))
```