---
title: "Korrelationen"
author: "Stefan Ahlers"
date: "13 11 2019"
output:
  html_document: 
    toc: true
    toc_float: true
    code_folding : hide
    df_print : paged
  pdf_document: default
---

```{r setupC, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
#library(sjPlot)
#library(sjlabelled)
#library(kableExtra)
#library(knitr)
library(apastats)
```


## Demografie
```{r cor_einstellung}

cor_einstellung <- data_demograph %>%  
                        inner_join(., data_kut, by="ResponseId") %>% 
                        inner_join(., data_RS_trust, by="ResponseId") %>% 
                        inner_join(., data_know_austria, by="ResponseId") %>% 
                        select(-ResponseId, -age_grp, -gender)

cor_einstellung %>% psych::pairs.panels(hist.col="skyblue", lm = T)
cor_einstellung %>% psych::corr.test()
```

## Demografie & Persönlichkeit

```{r cor_persoenlichkeit}
cor_demograph_pers <- data_demograph %>%  
                        inner_join(., data_bigFive, by="ResponseId") %>% 
                        select(-ResponseId, -age_grp, -gender)

cor_demograph_pers %>% psych::pairs.panels(hist.col="skyblue", lm = T)
cor_demograph_pers %>%  psych::corr.test()
```

## Korrelation Persönlichkeit

```{r cor_pers_einstellung}
cor_pers_einst <- data_bigFive %>%  
                        inner_join(., data_kut, by="ResponseId") %>% 
                        inner_join(., data_RS_trust, by="ResponseId") %>% 
                        inner_join(., data_know_austria, by="ResponseId") %>% 
                        select(-ResponseId)

cor_pers_einst %>% psych::pairs.panels(hist.col="skyblue", lm = T)
cor_pers_einst %>%  psych::corr.test()
```

## Anlernen
```{r cor_RS_anlernen}
cor_RS_anlernen <- data_demograph %>%  
                        select(ResponseId,age) %>% 
                        inner_join(., data_kut, by="ResponseId") %>% 
                        inner_join(., data_RS_trust, by="ResponseId") %>% 
                        inner_join(., data_anlernen, by="ResponseId") %>% 
                        select(-ResponseId)
  
cor_RS_anlernen %>%  psych::pairs.panels(hist.col="skyblue", lm = T)
cor_RS_anlernen %>%  psych::corr.test()
```

## UBCF
```{r cor_UBCF}
mrg_einsch_UBCF <- data_RS_einschaetzung %>%  select(ResponseId,einsch_UBCF_1)

cor_UBCF_demograph <- data_demograph %>%  
                        select(ResponseId,age,school,education) %>% 
                        inner_join(., mrg_einsch_UBCF, by="ResponseId") %>% 
                        inner_join(., data_UBCF, by="ResponseId") %>% 
                        select(-ResponseId)

cor_UBCF_bigFive <- data_bigFive %>%  
                        inner_join(., mrg_einsch_UBCF, by="ResponseId") %>% 
                        inner_join(., data_UBCF, by="ResponseId") %>% 
                        select(-ResponseId)

cor_UBCF_einstell <- data_kut %>% 
                        inner_join(., data_RS_trust, by="ResponseId") %>% 
                        inner_join(., data_know_austria, by="ResponseId") %>% 
                        inner_join(., mrg_einsch_UBCF, by="ResponseId") %>% 
                        inner_join(., data_UBCF, by="ResponseId") %>% 
                        select(-ResponseId)
  
cor_UBCF_einstell %>%  psych::corr.test()

cor_UBCF_einsch <- data_RS_einschaetzung %>% 
                     inner_join(., data_UBCF, by="ResponseId") %>% 
                     select(-ResponseId)

# Korrelation zwischen den Bewertungen
cor_UBCF_einsch  %>% select(UBCF_RS_bew, UBCF_ArticleReview_quality, UBCF_SUM_Artikel)  %>%  psych::pairs.panels(hist.col="skyblue", lm = T)
cor_UBCF_einsch  %>% select(UBCF_RS_bew, einsch_UBCF_1, UBCF_ArticleReview_quality, UBCF_SUM_Artikel)  %>%   psych::corr.test()
```

## SVD
```{r cor_SVD}
mrg_einsch_SVD <- data_RS_einschaetzung %>%  select(ResponseId,einsch_IBCF_1)

cor_SVD_demograph <- data_demograph %>%  
                        select(ResponseId,age,school,education) %>% 
                        inner_join(., mrg_einsch_SVD, by="ResponseId") %>% 
                        inner_join(., data_SVD, by="ResponseId") %>% 
                        select(-ResponseId)

cor_SVD_bigFive <- data_bigFive %>%  
                        inner_join(., mrg_einsch_SVD, by="ResponseId") %>% 
                        inner_join(., data_SVD, by="ResponseId") %>% 
                        select(-ResponseId)

cor_SVD_einstell <- data_kut %>% 
                        inner_join(., data_RS_trust, by="ResponseId") %>% 
                        inner_join(., data_know_austria, by="ResponseId") %>% 
                        inner_join(., mrg_einsch_SVD, by="ResponseId") %>% 
                        inner_join(., data_SVD, by="ResponseId") %>% 
                        select(-ResponseId)

cor_SVD_bigFive  %>%  psych::corr.test()


cor_SVD_einsch <- data_RS_einschaetzung %>% 
                     inner_join(., data_SVD, by="ResponseId") %>% 
                     select(-ResponseId)

cor_SVD_einsch  %>%  psych::pairs.panels(hist.col="skyblue", lm = T)
cor_SVD_einsch  %>%  psych::corr.test()

cor_SVD_einsch  %>% select(SVD_RS_bew, SVD_ArticleReview_quality, SVD_SUM_Artikel)  %>%  psych::pairs.panels(hist.col="skyblue", lm = T)
cor_SVD_einsch  %>% select(SVD_RS_bew, einsch_IBCF_1, SVD_ArticleReview_quality, SVD_SUM_Artikel)  %>%   psych::corr.test()
describe.mean.sd(cor_SVD_einsch$einsch_UBCF_1)
```

## Predictions UBCF

```{r cor_predictions_UBCF}

cor_pred_UBCF <- data_demograph %>%  
                        select(ResponseId,age) %>%
                        inner_join(., data_kut, by="ResponseId") %>% 
                        inner_join(., data_RS_trust, by="ResponseId") %>% 
                        inner_join(., data_bigFive, by="ResponseId") %>% 
                        inner_join(., data_article_UBCF, by="ResponseId") 

cor_pred_UBCF %>%  select(age, cor_user_UBCF_pre)  %>%  psych::pairs.panels(hist.col="skyblue", lm=TRUE)
cor_pred_UBCF %>%  select(age, cor_user_UBCF_post)  %>%  psych::pairs.panels(hist.col="skyblue", lm=TRUE)
cor_pred_UBCF %>%  select(age, user_pre_abstand_abs_UBCF)  %>%  psych::pairs.panels(hist.col="skyblue", lm=TRUE)
cor_pred_UBCF %>%  select(age, user_post_abstand_abs_UBCF)  %>%  psych::pairs.panels(hist.col="skyblue", lm=TRUE)

ggstatsplot::ggcorrmat(cor_pred_UBCF, 
                       cor.vars = c(age,KUT,RS_Privacy_Trust,cor_user_UBCF_pre, cor_user_UBCF_post,user_pre_abstand_abs_UBCF,user_post_abstand_abs_UBCF),
                       cor.vars.names = c("Alter","KUT","Trust","Korrelation Pretest", "Korrelation Posttest","Abstand Pretest","Abstand Posttest"),
                       hc.order = T)

ggstatsplot::ggcorrmat(cor_pred_UBCF, 
                       cor.vars = c(neuro,vertraeglich,extraversion,gewissenhaft,offenheit,cor_user_UBCF_pre, cor_user_UBCF_post,user_pre_abstand_abs_UBCF,user_post_abstand_abs_UBCF),
                       cor.vars.names = c("Neurotisch","Verträglichkeit","Extraversion","Gewissenhaftigkeit","Offenheit","Korrelation Pretest", "Korrelation Posttest","Abstand Pretest","Abstand Posttest"),
                       hc.order = T)
```

## Predictions SVD

```{r cor_predictions_SVD}

cor_pred_SVD <- data_demograph %>%  
                        select(ResponseId,age) %>%
                        inner_join(., data_kut, by="ResponseId") %>% 
                        inner_join(., data_RS_trust, by="ResponseId") %>% 
                        inner_join(., data_bigFive, by="ResponseId") %>% 
                        inner_join(., data_article_SVD, by="ResponseId") 

cor_pred_SVD %>%  select(age, cor_user_SVD_pre)  %>%  psych::pairs.panels(hist.col="skyblue", lm=TRUE)
cor_pred_SVD %>%  select(age, cor_user_SVD_post)  %>%  psych::pairs.panels(hist.col="skyblue", lm=TRUE)
cor_pred_SVD %>%  select(age, user_pre_abstand_abs_SVD)  %>%  psych::pairs.panels(hist.col="skyblue", lm=TRUE)
cor_pred_SVD %>%  select(age, user_post_abstand_abs_SVD)  %>%  psych::pairs.panels(hist.col="skyblue", lm=TRUE)

ggstatsplot::ggcorrmat(cor_pred_SVD, 
                       cor.vars = c(age,KUT,RS_Privacy_Trust,cor_user_SVD_pre, cor_user_SVD_post,user_pre_abstand_abs_SVD,user_post_abstand_abs_SVD),
                       cor.vars.names = c("Alter","KUT","Trust","Korrelation Pretest", "Korrelation Posttest","Abstand Pretest","Abstand Posttest"),
                       hc.order = T)

ggstatsplot::ggcorrmat(cor_pred_SVD, 
                       cor.vars = c(neuro,vertraeglich,extraversion,gewissenhaft,offenheit,cor_user_SVD_pre, cor_user_SVD_post,user_pre_abstand_abs_SVD,user_post_abstand_abs_SVD),
                       cor.vars.names = c("Neurotisch","Verträglichkeit","Extraversion","Gewissenhaftigkeit","Offenheit","Korrelation Pretest", "Korrelation Posttest","Abstand Pretest","Abstand Posttest"),
                       hc.order = T)

```

